const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Spritefont2,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Cnds.EveryTick,
		C3.JavaScriptInEvents.Start_Event2_Act1,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{fundo: 0},
	{telaJogo: 0},
	{fim: 0},
	{ArrastarSoltar: 0},
	{personagem: 0},
	{linha: 0},
	{telagameover: 0},
	{gameover: 0},
	{playagain: 0},
	{telastart: 0},
	{Mouse: 0},
	{terror: 0},
	{final: 0},
	{ganhou: 0},
	{reeinicar: 0},
	{start: 0},
	{susto: 0},
	{sim: 0},
	{nao: 0},
	{PlanoDeFundoEmBlocos: 0},
	{sim2: 0},
	{nao2: 0},
	{obrigado: 0},
	{sair: 0},
	{voltar: 0}
];

self.InstanceType = {
	fundo: class extends self.ITiledBackgroundInstance {},
	telaJogo: class extends self.ISpriteInstance {},
	fim: class extends self.ISpriteInstance {},
	personagem: class extends self.ISpriteInstance {},
	linha: class extends self.ISpriteInstance {},
	telagameover: class extends self.ITiledBackgroundInstance {},
	gameover: class extends self.ISpriteFontInstance {},
	playagain: class extends self.ISpriteFontInstance {},
	telastart: class extends self.ITiledBackgroundInstance {},
	Mouse: class extends self.IInstance {},
	terror: class extends self.ITiledBackgroundInstance {},
	final: class extends self.ITiledBackgroundInstance {},
	ganhou: class extends self.ISpriteFontInstance {},
	reeinicar: class extends self.ISpriteFontInstance {},
	start: class extends self.ISpriteInstance {},
	susto: class extends self.IInstance {},
	sim: class extends self.ISpriteFontInstance {},
	nao: class extends self.ISpriteFontInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	sim2: class extends self.ISpriteFontInstance {},
	nao2: class extends self.ISpriteFontInstance {},
	obrigado: class extends self.ISpriteFontInstance {},
	sair: class extends self.ISpriteFontInstance {},
	voltar: class extends self.ISpriteFontInstance {}
}